Repository Litminka/LitminkaApi, pull requests merged in 2024-03, with the labels that each got.

#27 Добавление логгера winston
  .env.example
  .gitignore
  TODO.md
  package-lock.json
  package.json
  prisma/seed.ts
  src/controllers/ShikimoriController.ts
  src/controllers/UserController.ts
  src/controllers/WatchListController.ts
  src/errors/ForbiddenError.ts
  src/errors/UnauthorizedError.ts
  src/index.ts
  src/loggerConf.ts
  src/middleware/errorHandler.ts
  src/models/RefreshToken.ts
  src/models/User.ts
  src/queues/autocheck.ts
  src/queues/shikimoriUpdate.ts
  src/services/AutoCheckService.ts
  src/services/KodikApiService.ts
  src/services/UserService.ts
  src/ts/index.d.ts
Labels: feature

#35 Follow Refactor
  src/controllers/FollowController.ts
  src/models/Follow.ts
  src/models/User.ts
  src/services/FollowService.ts
  src/ts/enums.ts
  src/ts/index.d.ts
Labels: feature, refactor

#36 Получение уведомлений (общий список и пользователей)
  src/controllers/NotificationController.ts
  src/helper/period.ts
  src/index.ts
  src/routes/NotificationRouter.ts
  src/services/NotificationService.ts
  src/validators/BaseValidator.ts
  src/validators/PeriodValidator.ts
  thunder-collection_litminka-api.json
Labels: feature

#38 Разделение методов на публичные и приватные
  src/routes/AnimeRouter.ts
  src/routes/FollowRouter.ts
  src/routes/NotificationRouter.ts
  src/routes/ShikimoriRouter.ts
  src/routes/UserRouter.ts
  src/routes/WatchListRouter.ts
  src/validators/BaseValidator.ts
Labels: refactor

#43 refactor: delete unused import, add return type
  src/controllers/NotificationController.ts
Labels: refactor

#46 fix: fix ssl parameter
  src/index.ts
Labels: bug

#52 TheaseMeanse/issue23
  src/controllers/FollowController.ts
  src/controllers/NotificationController.ts
  src/controllers/ShikimoriController.ts
  src/controllers/WatchListController.ts
  src/controllers/anime/AnimeController.ts
  src/controllers/anime/AnimeSearchController.ts
  src/helper/period.ts
  src/index.ts
  src/queues/shikimoriUpdate.ts
  src/requests/AnimeSearchRequest.ts
  src/requests/Request.ts
  src/requests/group/invite/GetInvitesRequest.ts
  src/requests/group/member/GetMemberGroupRequest.ts
  src/requests/group/member/LeaveGroupRequest.ts
  src/requests/watchList/DeleteFromWatchListValidation.ts
  src/routes/GroupListRouter.ts
  src/routes/SearchRouter.ts
  src/routes/anime/AnimeRouter.ts
  src/services/WatchListService.ts
  src/services/anime/AnimeService.ts
  src/services/anime/AnimeUpdateService.ts
  src/services/filters/AnimeSearchFilter.ts
  src/services/shikimori/ShikimoriApiService.ts
  src/services/shikimori/ShikimoriLinkService.ts
  src/validators/AnimeValidator.ts
  src/validators/BaseValidator.ts
  src/validators/FollowValidator.ts
  src/validators/GroupListValidator.ts
  src/validators/PaginationValidator.ts
  src/validators/PeriodValidator.ts
Labels: feature, difficult

#66 Фикс валидатора уведомлений
  src/validators/NotificationValidator.ts
Labels: bug, refactor

#69 Даунгрейд экспресс с беты 5.0.0 до 4.18.3 (CVE-2022-24999)
  package-lock.json
  package.json
Labels: help wanted, simple, vulnerability

#70 Обновление follow-redirects до 1.15.6 (CVE-2024-28849)
  package-lock.json
  package.json
Labels: simple, vulnerability

#71 Added list filters
  src/controllers/WatchListController.ts
  src/controllers/group/GroupAnimeListController.ts
  src/models/AnimeList.ts
  src/requests/group/animeList/GetGroupAnimeListRequest.ts
  src/requests/watchList/GetWatchListRequest.ts
  src/services/WatchListService.ts
  src/services/group/GroupAnimeListService.ts
  src/ts/index.d.ts
  src/validators/WatchListValidator.ts
Labels: feature

#72 Стандартизация конвенции имён валидаторов
  src/middleware/validatorError.ts
  src/middleware/validatorNotFound.ts
  src/requests/AnimeRequest.ts
  src/requests/Request.ts
  src/requests/follows/FollowAnimeRequest.ts
  src/requests/follows/UnfollowAnimeRequest.ts
  src/requests/group/animeList/AddGroupAnimeListRequest.ts
  src/requests/group/animeList/DeleteGroupAnimeListRequest.ts
  src/requests/group/animeList/GetGroupAnimeListRequest.ts
  src/requests/group/animeList/UpdateGroupAnimeListRequest.ts
  src/requests/group/invite/AcceptInviteRequest.ts
  src/requests/group/invite/DeleteInviteRequest.ts
  src/requests/group/invite/DenyInviteRequest.ts
  src/requests/group/invite/SendInviteRequest.ts
  src/requests/group/list/DeleteGroupRequest.ts
  src/requests/group/member/GetGroupMembersRequest.ts
  src/requests/group/member/LeaveGroupRequest.ts
  src/requests/group/member/UpdateMemberStateRequest.ts
  src/requests/notifications/GetNotificationsRequest.ts
  src/requests/notifications/GetUserNotificationsRequest.ts
  src/requests/notifications/ReadNotificationsRequest.ts
  src/requests/shikimoriLink/ShikimoriLinkRequest.ts
  src/requests/user/LoginUserRequest.ts
  src/requests/user/RegisterUserRequest.ts
  src/requests/watchList/AddToWatchListRequest.ts
  src/requests/watchList/DeleteFromWatchListRequest.ts
  src/requests/watchList/EditWatchListRequest.ts
  src/routes/WatchListRouter.ts
  src/validators/AnimeValidator.ts
  src/validators/BaseValidator.ts
  src/validators/FollowValidator.ts
  src/validators/GroupListValidator.ts
  src/validators/NotificationValidator.ts
  src/validators/ShikimoriValidator.ts
  src/validators/UserValidator.ts
  src/validators/WatchListValidator.ts
Labels: documentation, refactor

#76 TheaseMeanse/issue15
  package.json
  prisma/migrations/20240316171051_add_score_column_to_anime/migration.sql
  prisma/migrations/20240317134040_rename_score_to_rating_columns/migration.sql
  prisma/schema.prisma
  prisma/seed.ts
  src/config.ts
  src/controllers/anime/AnimeController.ts
  src/models/Anime.ts
  src/models/AnimeRelations.ts
  src/queues/ratingUpdate.ts
  src/requests/GetTopAnimeRequest.ts
  src/routes/AnimeRouter.ts
  src/routes/anime/AnimeRouter.ts
  src/services/anime/AnimeService.ts
  src/services/anime/AnimeUpdateService.ts
  src/services/filters/AnimeSearchFilter.ts
  src/services/shikimori/ShikimoriApiService.ts
  src/validators/BaseValidator.ts
  tsconfig.json
Labels: feature

#85 fix: remove extra import
  src/controllers/anime/AnimeController.ts
Labels: bug, refactor

#91 refactor: remove search router
  src/index.ts
  src/routes/SearchRouter.ts
  src/routes/anime/AnimeRouter.ts
Labels: refactor
